// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHudB2ezNeWd7dt2MQaIrIR0qty49v0xI',
    appId: '1:288886376879:web:b2af5e4192aa46fd48475a',
    messagingSenderId: '288886376879',
    projectId: 'eizesong',
    authDomain: 'eizesong.firebaseapp.com',
    storageBucket: 'eizesong.firebasestorage.app',
    measurementId: 'G-Q3N1P42XKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNoz2w-7mY1iuDot-S0ssPug2dZ0QWIBQ',
    appId: '1:288886376879:android:c6be1b8e32e2089d48475a',
    messagingSenderId: '288886376879',
    projectId: 'eizesong',
    storageBucket: 'eizesong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoHsPPruP7gvQWZKCnWK6APeZ9gsQ-JMU',
    appId: '1:288886376879:ios:d3688e14b78bf00648475a',
    messagingSenderId: '288886376879',
    projectId: 'eizesong',
    storageBucket: 'eizesong.firebasestorage.app',
    iosBundleId: 'com.eizesong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoHsPPruP7gvQWZKCnWK6APeZ9gsQ-JMU',
    appId: '1:288886376879:ios:fd6f6490ba9a33bf48475a',
    messagingSenderId: '288886376879',
    projectId: 'eizesong',
    storageBucket: 'eizesong.firebasestorage.app',
    iosBundleId: 'com.example.songGuessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHudB2ezNeWd7dt2MQaIrIR0qty49v0xI',
    appId: '1:288886376879:web:0716d0aea492d4f048475a',
    messagingSenderId: '288886376879',
    projectId: 'eizesong',
    authDomain: 'eizesong.firebaseapp.com',
    storageBucket: 'eizesong.firebasestorage.app',
    measurementId: 'G-77ZS08RLEY',
  );
}
